# Generated by Django 5.1.7 on 2025-04-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=128, verbose_name='نام (دری)')),
                ('name_ps', models.CharField(max_length=128, verbose_name='نام (پشتو)')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=128, verbose_name='تگ (دری)')),
                ('name_ps', models.CharField(max_length=128, verbose_name='تگ (پشتو)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام محصول (دری)')),
                ('name_ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول (پشتو)')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات (دری)')),
                ('description_ps', models.TextField(blank=True, verbose_name='توضیحات (پشتو)')),
                ('city', models.CharField(max_length=128, verbose_name='شهر')),
                ('seller_contact', models.CharField(max_length=100, verbose_name='اطلاعات تماس فروشنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید توسط ادمین')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazarche_app.category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, to='bazarche_app.tag', verbose_name='تگ\u200cها')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='توضیح عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bazarche_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='bazarche_app.product')),
            ],
        ),
    ]
