# Generated by Django 5.0.2 on 2025-05-27 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0003_alter_category_name_en_alter_category_name_fa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام (فارسی)')),
                ('name_ps', models.CharField(blank=True, max_length=100, verbose_name='نام (پشتو)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام (انگلیسی)')),
                ('icon', models.CharField(default='bi-tag', help_text='نام آیکون از Bootstrap Icons', max_length=50)),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اصلی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اصلی',
                'ordering': ['order', 'name_fa'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(choices=[('0-1000', '0 - 1,000 افغانی'), ('1000-5000', '1,000 - 5,000 افغانی'), ('5000-10000', '5,000 - 10,000 افغانی'), ('10000-50000', '10,000 - 50,000 افغانی'), ('50000-100000', '50,000 - 100,000 افغانی'), ('100000+', 'بیش از 100,000 افغانی')], default='0-1000', max_length=20, verbose_name='رنج قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazarche_app.maincategory', verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام (فارسی)')),
                ('name_ps', models.CharField(blank=True, max_length=100, verbose_name='نام (پشتو)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام (انگلیسی)')),
                ('icon', models.CharField(default='bi-tag', help_text='نام آیکون از Bootstrap Icons', max_length=50)),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bazarche_app.maincategory', verbose_name='دسته\u200cبندی اصلی')),
            ],
            options={
                'verbose_name': 'زیردسته\u200cبندی',
                'verbose_name_plural': 'زیردسته\u200cبندی\u200cها',
                'ordering': ['order', 'name_fa'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazarche_app.subcategory', verbose_name='زیردسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
