# Generated by Django 5.0.2 on 2025-05-28 08:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0004_maincategory_product_price_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name_fa'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', help_text='نام آیکون از Bootstrap Icons', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bazarche_app.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, verbose_name='نام (فارسی)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ps',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام (پشتو)'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name_ps',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام (پشتو)'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazarche_app.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات (فارسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ps',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات (پشتو)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='تخفیف\u200cدار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=200, verbose_name='نام (فارسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ps',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام (پشتو)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات تماس فروشنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bazarche_app.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_ps',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام (پشتو)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name_fa')},
        ),
    ]
