# Generated by Django 5.0.2 on 2025-06-01 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0006_city_alter_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_suggested',
            field=models.BooleanField(default=False, verbose_name='محصول پیشنهادی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_optional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
    ]
