# Generated by Django 5.0.2 on 2025-06-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0007_product_is_suggested_userprofile_last_name_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fake', 'محصول تقلبی'), ('inappropriate', 'محتوای نامناسب'), ('scam', 'کلاهبرداری'), ('duplicate', 'تکرار آگهی'), ('other', 'سایر')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='bazarche_app.product')),
            ],
            options={
                'verbose_name': 'گزارش تخلف',
                'verbose_name_plural': 'گزارش\u200cهای تخلف',
                'ordering': ['-created_at'],
            },
        ),
    ]
