# Generated by Django 5.0.2 on 2025-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0008_abusereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/', verbose_name='ویدیو')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('location', models.CharField(choices=[('home', 'صفحه اصلی'), ('products', 'صفحه محصولات')], max_length=20, verbose_name='موقعیت نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['-created_at'],
            },
        ),
    ]
