# Generated by Django 5.0.2 on 2025-07-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0011_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('home', 'صفحه اصلی'), ('products', 'بین محصولات'), ('sidebar', 'نوار کناری')], max_length=20, verbose_name='موقعیت نمایش'),
        ),
    ]
