# Generated by Django 5.0.2 on 2025-07-09 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0012_advertisement_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name_change',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_optional',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(default='', max_length=100, verbose_name='شماره تماس یا ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='simple_password_123', max_length=128, verbose_name='رمز عبور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شناسه کاربر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
    ]
