# Generated by Django 5.0.2 on 2025-07-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0013_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شغل')),
                ('description', models.TextField(verbose_name='توضیحات/مشخصات فنی کار')),
                ('contact', models.CharField(max_length=100, verbose_name='شماره تماس/راه ارتباطی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazarche_app.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'آگهی شغلی',
                'verbose_name_plural': 'آگهی\u200cهای شغلی',
                'ordering': ['-created_at'],
            },
        ),
    ]
