# Generated by Django 5.0.2 on 2025-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0014_jobad'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='owner_profile_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='شناسه کاربر'),
        ),
    ]
