# Generated by Django 5.0.2 on 2025-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0016_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='اگر هیچ شهری انتخاب نشود، تبلیغ در همه شهرها نمایش داده می\u200cشود.', to='bazarche_app.city', verbose_name='شهرها'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_cities',
            field=models.ManyToManyField(blank=True, help_text='اگر هیچ شهری انتخاب نشود، محصول در همه شهرها تخفیفی خواهد بود.', related_name='discounted_products', to='bazarche_app.city', verbose_name='شهرهای تخفیفی'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_cities',
            field=models.ManyToManyField(blank=True, help_text='اگر هیچ شهری انتخاب نشود، محصول در همه شهرها ویژه خواهد بود.', related_name='featured_products', to='bazarche_app.city', verbose_name='شهرهای ویژه'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_cities',
            field=models.ManyToManyField(blank=True, help_text='اگر هیچ شهری انتخاب نشود، محصول در همه شهرها پیشنهادی خواهد بود.', related_name='suggested_products', to='bazarche_app.city', verbose_name='شهرهای پیشنهادی'),
        ),
    ]
