# Generated by Django 5.0.2 on 2025-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarche_app', '0017_advertisement_cities_product_discounted_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'نو'), ('used', 'دست دوم')], default='new', max_length=10, verbose_name='وضعیت محصول'),
        ),
    ]
